# Generated by Django 4.0.3 on 2022-06-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesperson',
            name='sales',
            field=models.ManyToManyField(blank=True, to='sales_rest.record'),
        ),
    ]
