# Generated by Django 4.0.3 on 2022-06-20 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_salesperson_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='sales_rest.autovo'),
        ),
        migrations.AlterField(
            model_name='record',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='sales_rest.customer'),
        ),
        migrations.AlterField(
            model_name='record',
            name='sales_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='sales_rest.salesperson'),
        ),
    ]
