# Generated by Django 4.0.3 on 2022-06-21 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_record_sales_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesperson',
            name='sales',
        ),
    ]
